sonar.projectKey=catboy16669_Final_Project_devops
sonar.organization=catboy16669

sonar.projectName=AUPP LMS Website
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=assets/vendor/**,assets/img/**,**/*.map,**/*.min.js,**/*.min.css,terraform/**,.git/**,.github/**
sonar.inclusions=index.html,privacy.html,404.html,terms.html,portfolio-details.html,service-details.html,assets/js/main.js,assets/css/main.css