sonar.projectKey=catboy16669_Final_Project_devops
sonar.projectName=catboy16669
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=assets/vendor/**,assets/img/**,**/*.map,**/*.min.js,**/*.min.css,terraform/**,.git/**
sonar.inclusions=index.html,privacy.html,404.html,terms.html,assets/js/main.js,assets/css/main.css